name: Build Native
on:
  push:
    paths:
      - "native/**"
  pull_request:
    paths:
      - "native/**"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
            platform: linux
            artifact-path: native/bin/x11/liblobutil.so
          - name: Web
            os: ubuntu-24.04
            platform: javascript
            artifact-path: native/bin/javascript/liblobutil.wasm
          - name: Windows
            os: ubuntu-24.04
            platform: windows
            artifact-path: native/bin/win64/liblobutil.dll
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Cache Submodules
        uses: actions/cache@v4
        id: cache-submodules
        with:
          path: |
            native/lib
            native/godot-cpp
          key: ${{matrix.platform}}-submodules
      - name: Checkout submodules
        if: "${{steps.cache-submodules.outputs.cache-hit != 'true'}}"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Linux dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config

      - name: Web dependencies
        if: ${{ matrix.platform == 'javascript' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config emscripten

      - name: Windows dependencies
        if: ${{ matrix.platform == 'windows' }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64

      - name: Install scons
        run: |
          python -m pip install scons

      - name: Build
        run: |
          mkdir -p native/bin/x11 native/bin/win64 native/bin/javascript native/bin/osx
          scons --directory=native/ platform=${{matrix.platform}} target=release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "liblobutil-${{matrix.platform}}"
          path: ${{matrix.artifact-path}}
          if-no-files-found: error
